### ISSUE TITLE
What about app details after i got app id?

### ISSUE THREAD

**Issue by BonBonSlick** [babelshift/BetterSteamWebAPIDocumentation#2]
Hello, i think you have missed smth here http://steamwebapi.azurewebsites.net/

http://store.steampowered.com/api/appdetails?appids=10

**Comment by babelshift** [comment]
@BonBonSlick, unfortunately, since the page is dynamically generated based on the output of `https://api.steampowered.com/ISteamWebAPIUtil/GetSupportedAPIList/v1`, I can't control what is and isn't displayed.

I could think of how to incorporate store APIs which don't appear in the endpoint above.
