### ISSUE TITLE
the dev apikey is a parameter of GET, how to keep it secret ?

### ISSUE THREAD

**Issue by enjoecn** [babelshift/BetterSteamWebAPIDocumentation#3]
as the title.

**Comment by babelshift** [comment]
Don't expose the HTTP request to anyone using your application. If you're building a web app, you should build your own API which in turn calls the Steam Web API.

This way you can hide the key from the public.

**Comment by enjoecn** [comment]
got it. but yet can get the apikey by using net capture tools. 
thank u for your response.
