### ISSUE TITLE
Looking for discussion on adding friends to steamid from web api

### ISSUE THREAD

**Issue by jbevarts** [babelshift/BetterSteamWebAPIDocumentation#5]
Title says it all.  Curious if you looked into this when implementing your docs.

**Comment by babelshift** [comment]
The docs generated by the app in this repo are based on the results of calling the following endpoint. 
```
GET https://api.steampowered.com/ISteamWebAPIUtil/GetSupportedAPIList/v1
```

It should align closely with the official Steam Web API docs here: https://partner.steamgames.com/doc/webapi.

If you're looking to do more than read-only operations, then the Steam Web API won't help you. You'll have to use something like  [SteamKit2](https://github.com/SteamRE/SteamKit) which mimics the Steam client or sign up for the official [Steamworks SDK](https://partner.steamgames.com/doc/sdk).
